export const SPACE_CATALOG={
 "Nội thất":["HG tự đề xuất","Phòng khách","Phòng ăn","Bếp","Phòng ngủ Master","Phòng ngủ phụ","Phòng thay đồ","Phòng tắm","Phòng làm việc","Phòng trẻ em","Sảnh đón","Hành lang","Cầu thang","Lounge","Minibar","Phòng rượu & Cigar","Showroom","Nhà hàng","Quán cà phê","Khách sạn","Spa","Văn phòng","Phòng họp","Thư viện","Rạp phim","Garage Studio","Không gian thương mại","Khác"],
 "Kiến trúc":["HG tự đề xuất","Biệt thự đơn lập","Biệt thự song lập","Biệt thự nghỉ dưỡng","Nhà phố","Nhà ở riêng lẻ","Penthouse","Chung cư","Tòa nhà cao tầng","Khách sạn","Resort","Văn phòng","Trung tâm thương mại","Showroom","Nhà hàng","Café","Bảo tàng","Nhà triển lãm","Nhà hát","Trường học","Bệnh viện","Công trình công cộng","Công trình công nghiệp","Công trình văn hóa","Công trình ven biển","Công trình sinh thái","Công trình hỗn hợp","Mặt tiền","Sảnh kiến trúc","Sân trong","Mái và sân thượng","Khác"],
 "Cảnh quan":["HG tự đề xuất","Sân vườn biệt thự","Sân trong","Công viên","Quảng trường","Cảnh quan resort","Hồ bơi","Vườn trên mái","Vườn Nhật","Tropical Garden","Cảnh quan ven hồ","Ven sông","Ven biển","Lối dạo","Cảnh quan đô thị","Khác"],
 "Quy hoạch đô thị":["HG tự đề xuất","Tổng mặt bằng Masterplan","Khu đô thị","Khu dân cư","Khu nghỉ dưỡng","Khu công nghiệp","Khu hỗn hợp","Tổ hợp cao tầng","Quảng trường trung tâm","Trục cảnh quan","Đường phố","Công viên đô thị","Bờ sông đô thị","Bờ biển đô thị","Khu phố thương mại","Phân khu chức năng","Khác"]
};
export const STYLE_OPTIONS=["HG tự đề xuất","Minimal Luxury","Modern Luxury","Contemporary","Modern","Minimalist","Neo-Classic","American Neo-Classic","Classic","Art Deco","Art Nouveau","Wabi-Sabi","Japandi","Japanese","Zen","Scandinavian","Nordic","Bauhaus","Mid-Century Modern","Industrial","Loft","Brutalism","High-Tech","Futuristic","Parametric","Organic Architecture","Biophilic","Eco-Chic","Sustainable","Tropical","Tropical Coastal","Modern Coastal","Mediterranean","Santorini","Resort","Balinese","Indochine","Colonial","French Classic","French Contemporary","Italian Luxury","European Modern","American Modern","Farmhouse","Modern Farmhouse","Rustic","Country","Bohemian","Moroccan","Arabic","Islamic","Oriental","Chinese Contemporary","Korean Minimal","Vintage","Retro","Shabby Chic","Maximalism","Eclectic","Transitional","Glam","Hollywood Regency","Quiet Luxury","Warm Minimalism","Soft Minimalism","Monochrome","Black & White","Dark Luxury","Urban Chic","Gallery Style","Museum Style","Hospitality Luxury","Boutique Hotel","Yacht Interior","Smart Home","Space Age","Deconstructivism","Neo-Futurism","Tadao Ando Inspired","Tropical Modernism","Desert Modern","Alpine Chalet","Traditional Vietnamese","Contemporary Vietnamese","Custom"];
export const CAMERA_OPTIONS=["HG tự đề xuất","Giữ nguyên camera ảnh gốc","Eye Level","Low Angle","High Angle","Worm's Eye View","Bird's Eye View","Top-down 90°","Aerial / Drone","Isometric","Axonometric","One-point Perspective","Two-point Perspective","Three-point Perspective","Front Elevation","Side Elevation","Rear Elevation","Corner View","Diagonal Composition","Symmetrical Central","Wide Establishing","Medium Shot","Close-up Detail","Macro Material","Hero Shot","Human Perspective","Architectural Editorial","Cinematic Frame","35mm Lens","50mm Lens","24mm Wide","16mm Ultra-wide","Tilt-shift Architectural","Panorama","Khác"];
export const LIGHTING_OPTIONS=["HG tự đề xuất","Giữ nguyên ánh sáng ảnh gốc","Natural Daylight","Morning Soft Light","Noon Sunlight","Afternoon Daylight","Golden Hour","Blue Hour","Overcast Soft Light","Cloudy Diffused","Dawn","Dusk","Night Exterior","Night Interior","Warm Ambient 2700K","Warm White 3000K","Neutral 3500K","Neutral White 4000K","Cool White 5000K","Indirect Cove Lighting","Architectural Accent","Track Spotlight","Decorative Pendant","Chandelier","Wall Washer","Linear Lighting","Softbox Studio","Cinematic Contrast","Low-key","High-key","Moody Dark","Gallery Lighting","Hospitality Lighting","Mixed Natural + Artificial","RGB Ambient","Khác"];
export const ASPECT_OPTIONS=[["HG tự đề xuất","1536x1024"],["1:1 Vuông","1024x1024"],["3:2 Ngang","1536x1024"],["2:3 Dọc","1024x1536"],["4:3 Ngang","1536x1024"],["3:4 Dọc","1024x1536"],["5:4 Ngang","1536x1024"],["4:5 Dọc","1024x1536"],["16:9 Ngang","1536x1024"],["9:16 Dọc","1024x1536"],["16:10 Ngang","1536x1024"],["10:16 Dọc","1024x1536"],["21:9 Siêu rộng","1536x1024"],["9:21 Siêu dọc","1024x1536"],["2:1 Panorama","1536x1024"],["1:2 Dọc dài","1024x1536"],["3:1 Siêu panorama","1536x1024"],["1:3 Siêu dọc","1024x1536"],["A4 Dọc (1:√2)","1024x1536"],["A4 Ngang (√2:1)","1536x1024"],["4:3 Màn hình","1536x1024"],["1.85:1 Điện ảnh","1536x1024"],["2.39:1 CinemaScope","1536x1024"]];
export function recommendVisual(c){const exterior=["Kiến trúc","Cảnh quan","Quy hoạch đô thị"].includes(c.space);return {style:exterior?"Contemporary":"Minimal Luxury",camera:c.mode==="edit"&&c.masterImage?"Giữ nguyên camera ảnh gốc":c.space==="Quy hoạch đô thị"?"Aerial / Drone":exterior?"Two-point Perspective":"Eye Level",lighting:c.mode==="edit"&&c.masterImage?"Giữ nguyên ánh sáng ảnh gốc":exterior?"Afternoon Daylight":"Natural Daylight",zone:(SPACE_CATALOG[c.space]||[])[1]||"Không xác định"};}

export const FURNITURE_BRANDS=[
 ["Tự động & tùy chỉnh",["Không áp dụng","HG tự đề xuất","Thương hiệu khác (nhập tên)"]],
 ["Luxury & Haute Couture",["Longhi","Caracole","Fendi Casa","Bentley Home","Baxter","Visionnaire","Giorgetti","Turri","Cornelio Cappellini","Roberto Cavalli Home Interiors","Versace Home","Armani/Casa","Dolce&Gabbana Casa","Rugiano","Capital Collection","Signorini & Coco","Jumbo Collection","Savio Firmino","Provasi","Fratelli Boffi"]],
 ["Contemporary & Design",["Minotti","B&B Italia","Cassina","Poliform","Flexform","Molteni&C","Poltrona Frau","Lema","Ligne Roset","Roche Bobois","LAGO","Cattelan Italia","Bonaldo","Porro","Edra","Moroso","Kartell","MDF Italia","Living Divani","Zanotta","Arper","Vitra","Knoll","Herman Miller","USM","HAY","Muuto","Fritz Hansen","Carl Hansen & Søn","BoConcept","Walter Knoll","De Sede","Tacchini"]],
 ["Ánh sáng & Trang trí",["Flos","Artemide","Louis Poulsen","Foscarini","Bocci","Lasvit","Preciosa Lighting","Lalique","Baccarat","Tom Dixon","Moooi","Occhio","Vibia","Davide Groppi","Catellani & Smith"]],
 ["Ngoài trời & Thảm",["Dedon","Kettal","Roda","Paola Lenti","Tribù","Royal Botania","Gloster","Gandia Blasco","GAN Rugs","cc-tapis","Nanimarquina","Tai Ping","Missoni Home","Rug'Society"]],
 ["Bếp & Phòng tắm",["Boffi","Bulthaup","Poggenpohl","SieMatic","Valcucine","Arclinea","Dada","Gaggenau","Liebherr","Gessi","Antonio Lupi","Agape","Duravit","Villeroy & Boch"]]
];

export const OUTPUT_TYPES=
 ["HG tự đề xuất","Hình ảnh thực tế — Photorealistic","Ảnh chụp kiến trúc chuyên nghiệp — Architectural Photography","Ảnh chụp nội thất tạp chí — Editorial Interior Photography","Hình ảnh 3D — Photorealistic ArchViz","Render 3D — 3ds Max + Corona Renderer","Render 3D — 3ds Max + V-Ray","Render 3D — SketchUp + V-Ray","Render 3D — SketchUp + Enscape","Render 3D — D5 Render","Render 3D — Lumion","Render 3D — Twinmotion","Render 3D — Blender + Cycles","Render 3D — Unreal Engine","Hình ảnh 3D — Concept Design","Hình ảnh 3D — Clay / trắng vật liệu","Hình ảnh điện ảnh — Cinematic","Hình ảnh tạp chí — Editorial","Ảnh sản phẩm — Studio / Commercial","Tranh phác thảo — Architectural Sketch","Bản vẽ nét — Line Art","Tranh màu nước — Watercolor","Tranh gouache — Gouache Painting","Tranh sơn dầu — Oil Painting","Tranh chì — Pencil Drawing","Tranh marker — Marker Rendering","Ảnh cắt ghép — Architectural Collage","Sơ đồ ý tưởng — Concept Diagram"];
export const PHOTO_DIRECTIONS=["HG tự đề xuất","Ảnh kiến trúc thực tế — tự nhiên","Tạp chí kiến trúc cao cấp","Ảnh nội thất đời sống chân thực","Ảnh bất động sản chuyên nghiệp","Ảnh sản phẩm nội thất","Ánh sáng ban ngày trung tính","Ánh sáng chiều tự nhiên","Không gian đêm với đèn thực tế","Chi tiết vật liệu cận cảnh"];
export function resolvePhotoDirection(c){
 const real=["HG tự đề xuất","Hình ảnh thực tế — Photorealistic","Ảnh chụp kiến trúc chuyên nghiệp — Architectural Photography","Ảnh chụp nội thất tạp chí — Editorial Interior Photography"].includes(c.outputType||"HG tự đề xuất");
 const selected=c.photoDirection&&c.photoDirection!=="HG tự đề xuất"?c.photoDirection:(c.space==="Kiến trúc"?"Ảnh kiến trúc thực tế — tự nhiên":c.space==="Nội thất"?"Tạp chí kiến trúc cao cấp":"Ảnh kiến trúc thực tế — tự nhiên");
 return {real,selected,guide:real?"Professional architectural photographer direction: realistic full-frame camera response, plausible 24–50mm lens, level verticals, human-eye perspective, accurate white balance and exposure, natural window light and practical fixtures, physically plausible shadow softness and reflections, subtle sensor grain, credible material imperfections and lived-in styling. Avoid plastic textures, over-sharpening, excessive HDR, impossible geometry, duplicated props, artificial glow and exaggerated depth of field. Photographic plausibility is a visual target, not proof that the image is a real photograph.":"Respect the chosen visual medium and its characteristic rendering; retain correct scale, perspective, material behavior and lighting."};
}

export const AUTO_CONTEXT="HG tự xử lý";
export const SETTING_AREAS=["HG tự xử lý","Trung tâm thành phố","Khu dân cư đô thị","Ngoại ô","Vùng quê","Miền núi","Đồi cao","Thung lũng","Rừng","Ven sông","Ven hồ","Ven biển","Đảo","Cao nguyên","Sa mạc","Khu phố cổ","Khu di sản","Khu công nghiệp","Khác (mô tả)"];
export const WEATHER_CONTEXT=["HG tự xử lý","Trời quang","Nắng nhẹ","Nắng mạnh","Nhiều mây","Âm u","Mưa nhẹ","Mưa lớn","Sương mù","Tuyết","Sau cơn mưa"];
export const SEASON_CONTEXT=["HG tự xử lý","Mùa xuân","Mùa hè","Mùa thu","Mùa đông","Mùa mưa","Mùa khô"];
export const VIEW_CONTEXT={
 "Nội thất":["HG tự xử lý","Giữ nguyên bối cảnh qua cửa sổ","Phố đô thị qua cửa sổ","Vườn cây xanh","Sân trong","Cảnh núi","Cảnh biển","Cảnh hồ","Cảnh sông","Cảnh đồng quê","Cảnh đảo","Không nhìn thấy bên ngoài","Khác (mô tả)"],
 "Kiến trúc":["HG tự xử lý","Cảnh quan đô thị hiện hữu","Phố cổ","Khu biệt thự","Đồi núi","Rừng cây","Đồng quê","Ven biển","Đảo","Ven hồ","Ven sông","Cảnh quan nhiệt đới","Khác (mô tả)"],
 "Cảnh quan":["HG tự xử lý","Thảm thực vật bản địa","Công viên đô thị","Vườn biệt thự","Vùng núi","Đồng quê","Ven biển","Đảo","Ven sông","Ven hồ","Khác (mô tả)"],
 "Quy hoạch đô thị":["HG tự xử lý","Đô thị mật độ cao","Khu dân cư hiện hữu","Phố cổ","Đô thị ven biển","Đô thị ven sông","Đô thị miền núi","Vùng nông thôn","Đảo","Vùng sinh thái","Khác (mô tả)"]
};
export function validLocalDate(c={}){const {year,month,day}=c;if(!/^\d{4}$/.test(String(year||""))||!/^\d{1,2}$/.test(String(month||""))||!/^\d{1,2}$/.test(String(day||"")))return false;const d=new Date(Date.UTC(Number(year),Number(month)-1,Number(day)));return d.getUTCFullYear()===Number(year)&&d.getUTCMonth()+1===Number(month)&&d.getUTCDate()===Number(day)}
export function geographicDirection(c={}){
 const clean=v=>typeof v==="string"&&v.trim()&&v.trim()!==AUTO_CONTEXT?v.trim():null;
 const country=clean(c.country),city=clean(c.city),area=clean(c.settingArea),scene=clean(c.surroundings),weather=clean(c.weather),season=clean(c.season),orientation=clean(c.orientation);
 const date=[c.year,c.month,c.day].every(x=>Number.isInteger(Number(x))&&Number(x)>0)?new Date(Date.UTC(Number(c.year),Number(c.month)-1,Number(c.day))):null;
 const dateOK=date&&validLocalDate(c);
 const time=/^([01]\d|2[0-3]):[0-5]\d$/.test(c.localTime||"")?c.localTime:null;
 const details=[country&&"Quốc gia: "+country,city&&"Thành phố: "+city,area&&"Địa hình/khu vực: "+area,scene&&"Bối cảnh nhìn thấy: "+scene,clean(c.contextNotes)&&"Chi tiết khu vực: "+clean(c.contextNotes),season&&"Mùa: "+season,weather&&"Thời tiết mong muốn: "+weather,dateOK&&"Ngày địa phương: "+[c.year,String(c.month).padStart(2,"0"),String(c.day).padStart(2,"0")].join("-"),time&&"Giờ địa phương: "+time,orientation&&"Hướng nhìn/công trình: "+orientation].filter(Boolean);
 return ["Use site-specific, plausible local architecture, vegetation, terrain, urban density, cultural details, seasonal daylight and environmental context. "+(details.length?details.join("; "):"HG chooses a visually appropriate plausible context."),"Interior: the view outside windows and daylight must match the site; Architecture: surrounding landscape, streets and terrain must match; Landscape: local ecology and plants must fit; Urban planning: settlement morphology and infrastructure must fit.","Do not invent a verified real address, live weather, exact sun position, landmarks or site-specific facts. Exact solar angle and weather require verified coordinates, orientation, date/time and data. Preserve master image geography, views, camera and locked elements in edit mode unless explicitly authorized."].join(" ");
}
