import {designAudit} from "./design-brain.js";
import {VERSION,MODULES,SPACES,STYLES,EXPERTS,MATERIALS,newProject,safeText,validateProject,area,boq,promptQuality,compilePrompt,csv,formatVnd} from "./core.js";
const $=s=>document.querySelector(s),view=$("#view"),KEY="hg-studio-ai-projects-v1",ACTIVE="hg-studio-ai-active-v1";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let storeOk=true,projects=[],active="",route="home",moduleId="design",visionFile=null,upscaleFile=null,visionData=null,upscaleUrl=null,toastTimer=null;
function seed(){try{let raw=JSON.parse(localStorage.getItem(KEY)||"[]");projects=Array.isArray(raw)?raw.filter(validateProject).slice(0,80):[];active=localStorage.getItem(ACTIVE)||"";}catch(e){storeOk=false;projects=[];}if(!projects.length){projects=[newProject("Dự án đầu tiên")];save();}if(!projects.some(p=>p.id===active))active=projects[0].id;}
function project(){return projects.find(p=>p.id===active)||projects[0];}
function save(){try{localStorage.setItem(KEY,JSON.stringify(projects));localStorage.setItem(ACTIVE,active);storeOk=true;}catch(e){storeOk=false;notify("Bộ nhớ đầy hoặc bị chặn. Hãy xuất bản sao JSON.");}}
function touch(){project().updated=new Date().toISOString();save();}
function notify(msg){let t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),3700);}
function download(text,name,mime="text/plain;charset=utf-8"){let url=URL.createObjectURL(new Blob([text],{type:mime}));let a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200);}
const VI_OPTIONS={"create":"Tạo thiết kế mới","edit":"Chỉnh sửa / đồng bộ","yes":"Có","no":"Không","Natural Daylight":"Ánh sáng tự nhiên ban ngày","Slow Dolly":"Máy quay tiến chậm","Orbit":"Quay vòng quanh","Tracking":"Di chuyển bám theo","Static":"Máy quay cố định","Crane":"Nâng hạ máy quay","Push In":"Tiến gần","Furniture / Citterio":"Chuyên gia nội thất / Citterio","Material / Zumthor":"Chuyên gia vật liệu / Zumthor","Lighting / Ingo Maurer":"Chuyên gia ánh sáng / Ingo Maurer","Camera / Iwan Baan":"Chuyên gia góc máy / Iwan Baan","Removal":"Loại bỏ đối tượng","AspectRatio":"Tỷ lệ khung hình","ReferenceReplica":"Tái tạo theo ảnh tham chiếu","SpaceSync":"Đồng bộ không gian","Storyboard":"Kịch bản phân cảnh","Minimal Luxury":"Sang trọng tối giản","Contemporary":"Đương đại","Modern":"Hiện đại","Neo Classic":"Tân cổ điển","Wabi-Sabi":"Mộc mạc Wabi-Sabi","Japandi":"Nhật Bản – Bắc Âu","Luxury":"Sang trọng","Bauhaus":"Bauhaus","Biophilic":"Thiết kế gần thiên nhiên","Tropical Coastal":"Nhiệt đới ven biển","Industrial":"Công nghiệp","Classic":"Cổ điển"};
const viOption=x=>VI_OPTIONS[x]||x;
function field(label,name,value="",opts=null,hint=""){const id="f-"+name;if(opts){return '<div class="field"><label for="'+id+'">'+esc(label)+'</label><select id="'+id+'" data-field="'+esc(name)+'">'+opts.map(o=>'<option value="'+esc(o)+'" '+(o===value?"selected":"")+'>'+esc(viOption(o))+'</option>').join("")+'</select>'+(hint?'<small>'+esc(hint)+'</small>':"")+'</div>';}return '<div class="field"><label for="'+id+'">'+esc(label)+'</label>'+(name==="brief"||name==="notes"?'<textarea id="'+id+'" data-field="'+esc(name)+'" placeholder="Nhập yêu cầu rõ ràng...">'+esc(value)+'</textarea>':'<input id="'+id+'" data-field="'+esc(name)+'" value="'+esc(value)+'" placeholder="'+esc(label)+'">')+(hint?'<small>'+esc(hint)+'</small>':"")+'</div>';}
function header(tag,title,subtitle,extra=""){return '<div class="hero"><div><span class="eyebrow">'+esc(tag)+'</span><h1>'+esc(title)+'</h1><p>'+esc(subtitle)+'</p></div>'+extra+'</div>';}
function statusBadge(s){return '<span class="pill '+(s==="limited"?"limit":s==="planned"?"planned":"")+'">'+(s==="planned"?"Chưa kết nối":s==="limited"?"Giới hạn":"Công cụ nội bộ")+'</span>';}
const ARTNAME={design:"Thiết kế không gian",edit:"Chỉnh sửa thiết kế",video:"Kịch bản video",upscale:"Nâng cấp hình ảnh",visual:"Trực quan hóa 3D",plan:"Bản vẽ & mặt bằng",material:"Vật liệu & màu sắc",boq:"Dự toán khối lượng",vision:"Phân tích hình ảnh",expert:"Bộ não chuyên gia"};
const ARTNOTE={design:"Lên ý tưởng kiến trúc và nội thất",edit:"Thay sản phẩm, vật liệu và ánh sáng",video:"Phân cảnh, chuyển động và góc máy",upscale:"Phóng ảnh và cải thiện độ rõ",visual:"Diễn họa không gian và ánh sáng",plan:"Mặt bằng, công năng và diện tích",material:"Phối vật liệu, màu và bề mặt",boq:"Bảng vật tư, khối lượng, chi phí",vision:"Nhận diện và phân tích ảnh",expert:"Phối hợp quyết định chuyên gia"};
const PHOTO={design:"design.jpg",edit:"edit.jpg",video:"video.jpg",upscale:"upscale.jpg",visual:"visual.jpg",plan:"plan.jpg",material:"material.jpg",boq:"boq.jpg",vision:"vision.svg",expert:"expert.svg"};
const CARDMODE={design:"Không gian 3D",edit:"Vật liệu & nội thất",video:"Góc máy / phân cảnh",upscale:"Chi tiết hình ảnh",visual:"Mô hình phối cảnh",plan:"Mặt bằng 3D",material:"Bảng mẫu vật liệu",boq:"Khối lượng & chi phí",vision:"Phân tích không gian",expert:"Quyết định thiết kế"};
const EXTERNAL_TOOLS={"design":"https://hoanggiaktsda-beep.github.io/da-studio/","edit":"https://hoanggiaktsda-beep.github.io/hoanggia-studioai/","video":"https://hoanggiaktsda-beep.github.io/prompt-ai-videos/","upscale":"https://hoanggiaktsda-beep.github.io/HG-UPSCALE-AI/"};
function tile(m,i=0){let img=PHOTO[m.id]||PHOTO.design;const href=EXTERNAL_TOOLS[m.id];const opening=href?'<a class="tile visual-tile" href="'+esc(href)+'" aria-label="Mở '+esc(ARTNAME[m.id]||m.vi)+' tại website riêng">':'<button class="tile visual-tile" data-open="'+esc(m.id)+'" type="button" aria-label="Mở '+esc(ARTNAME[m.id]||m.vi)+'">';return opening+'<div class="tile-art photo-tile tile-'+esc(m.id)+'" style="background-image:linear-gradient(0deg,#080d15b8 0%,#0c131d18 72%),url(./assets/tools/'+img+')"><span class="tile-index">'+String(i+1).padStart(2,"0")+'</span><span class="tile-icon">'+esc(m.icon)+'</span><span class="tile-art-label">'+esc(CARDMODE[m.id]||"HOANGGIA AI")+'</span></div><div class="tile-info"><h3>'+esc(ARTNAME[m.id]||m.vi)+'</h3><p>'+esc(ARTNOTE[m.id]||m.vi)+'</p><div class="tile-bottom"><span>'+esc(ARTNAME[m.id]||m.vi)+'</span>'+statusBadge(m.status)+'</div></div>'+(href?"</a>":"</button>");}
function shell(content){view.innerHTML='<div class="content">'+content+'</div>';$("#projectSelect").innerHTML=projects.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===active?"selected":"")+'>'+esc(p.name.slice(0,42))+'</option>').join("");document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle("active",b.dataset.route===route));let names={home:"TỔNG QUAN",creative:"XƯỞNG SÁNG TẠO",intelligence:"TRÍ TUỆ AI",library:"THƯ VIỆN",projects:"DỰ ÁN",system:"HỆ THỐNG"};$("#crumb").textContent=names[route]||"HOANGGIA STUDIO";}
function renderHome(){let recent=[...projects].sort((a,b)=>String(b.updated||"").localeCompare(String(a.updated||""))).slice(0,4);let tools=MODULES.filter(x=>x.group==="creative"||x.group==="technical");shell(
'<div class="studio-heading"><div><span class="eyebrow">HOANGGIA / KHÔNG GIAN SÁNG TẠO</span><h1>Bộ công cụ AI</h1><p>Tất cả công cụ kiến trúc, nội thất và hình ảnh trong một không gian làm việc.</p></div><button class="btn btn-gold" id="projectCreate">＋ Dự án mới</button></div>'+
'<div class="dashboard-layout"><div class="dashboard-main"><div class="tool-gallery">'+tools.map((m,i)=>tile(m,i)).join("")+'</div><section class="studio-banner" aria-label="HOANGGIA STUDIO"><div class="banner-content"><span class="eyebrow">HOANGGIA / TRÍ TUỆ THIẾT KẾ</span><h2>Không gian sáng tạo.<br><em>Không giới hạn ý tưởng.</em></h2><p>Từ ý tưởng đầu tiên đến thiết kế hoàn thiện — kiến trúc, nội thất và hình ảnh trong một Studio.</p><div class="banner-actions"><a class="btn btn-gold" href="https://hoanggiaktsda-beep.github.io/da-studio/">Khám phá Studio ↗</a><span class="banner-index">01 / THIẾT KẾ · CHỈNH SỬA · DIỄN HỌA</span></div></div><div class="banner-visual" aria-hidden="true"><span class="banner-visual-caption">HOANGGIA STUDIO — ARCHITECTURE / AI</span></div></section></div>'+
'<aside class="dashboard-aside"><div class="recent-panel"><div class="section-title"><h2>Dự án gần đây</h2><button class="btn btn-small" data-route="projects">Xem tất cả →</button></div>'+recent.map(p=>'<button class="recent-row" data-project="'+esc(p.id)+'"><span class="recent-thumb"></span><span><strong>'+esc(p.name)+'</strong><small>'+esc(p.space||"Nội thất")+' · '+esc(new Date(p.updated).toLocaleDateString("vi-VN"))+'</small></span><span class="recent-arrow">↗</span></button>').join("")+'<button class="btn btn-wide" data-route="projects">Quản lý dự án</button></div><div class="summary-panel"><span class="eyebrow">TRẠNG THÁI HỆ THỐNG</span><div><strong>'+projects.length+'</strong><span>Dự án</span></div><div><strong>'+MODULES.length+'</strong><span>Phân hệ</span></div><div><strong>V'+VERSION+'</strong><span>Phiên bản</span></div><p>AI chưa tích hợp thực được ghi rõ trạng thái trong từng công cụ.</p></div></aside></div>');}
function renderCreative(){let items=MODULES.filter(m=>m.group==="creative"||m.group==="technical");shell(header("KHÔNG GIAN SÁNG TẠO","Xưởng sáng tạo","Chọn công cụ theo nhiệm vụ; dữ liệu thiết kế được lưu trong cùng dự án.")+'<div class="tool-gallery">'+items.map((m,i)=>tile(m,i)).join("")+'</div>');}
function renderIntelligence(){const parts=[["Bộ não chuyên gia","Bộ quy tắc chuyên gia", "Đang hoạt động dưới dạng quy tắc kiểm định prompt."],["Bộ máy thị giác","Nhận biết thông tin ảnh", "Chỉ phân tích kích thước, màu sắc và độ sáng điểm ảnh; chưa có mô hình phân đoạn đối tượng."],["Trí tuệ không gian","Trí tuệ không gian","Diện tích từ số đo người dùng; chưa tự đo từ ảnh."],["Phản biện thiết kế","Phản biện thiết kế","Cảnh báo xung đột điều kiện và đầu vào thiếu."],["Bộ biên soạn yêu cầu","Biên dịch prompt","Xuất cấu trúc rõ ràng, giữ ràng buộc kiến trúc/camera."],["Bộ nhớ dự án","Bộ nhớ dự án","Lưu cục bộ, xuất/nhập JSON."],["Kiểm định chất lượng","Kiểm định chất lượng","Kiểm định đầu vào; chưa kiểm tra kết quả render của mô hình bên ngoài."],["Điều phối quy trình","Điều phối quy trình","Lưu trong cùng dự án; liên thông hai chiều giữa website độc lập chưa hoàn tất."]];
shell(header("BỘ NÃO DÙNG CHUNG","Trí tuệ AI","Các chức năng dùng chung với trạng thái thực tế và giới hạn kỹ thuật minh bạch.")+'<div class="grid g2">'+parts.map((p,i)=>'<div class="panel"><span class="eyebrow">BỘ NÃO 0'+(i+1)+'</span><h3>'+p[0]+'</h3><p>'+p[1]+'</p><div class="notice">'+p[2]+'</div></div>').join("")+'</div><div class="section-title"><h2>Phân tích điểm ảnh</h2></div><button class="btn btn-gold" data-open="vision">Mở phân tích hình ảnh →</button>');}
const MATERIAL_SPECS=[
{terms:["travertine"],query:"travertine"},
{terms:["calacatta"],query:"calacatta marble"},
{terms:["oak"],query:"oak wood veneer"},
{terms:["walnut"],query:"walnut wood veneer"},
{terms:["brushed","brass"],query:"brushed brass metal"},
{terms:["saddle","leather"],query:"saddle leather"},
{terms:["linen"],query:"linen fabric"},
{terms:["smoked","glass"],query:"smoked glass"}
];
// Lightweight CSS 3D samples: no image binaries, no generic room photography.
function materialSample(box,i){if(!box)return;box.classList.add("material-sample","material-sample-"+i);box.replaceChildren();const stage=document.createElement("div");stage.className="material-stage";const tile=document.createElement("div");tile.className="material-tile";stage.append(tile);box.append(stage);const label=document.createElement("span");label.className="material-preview-note";label.textContent="Mô phỏng 3D · Màu/vân tham khảo";box.append(label);}
let materialIndex=null,materialIndexPromise=null;
function materialSearchUrl(i){return "https://polyhaven.com/textures?q="+encodeURIComponent(MATERIAL_SPECS[i].query);}
function materialAlternateUrl(i){return "https://ambientcg.com/list?search="+encodeURIComponent(MATERIAL_SPECS[i].query);}
function materialMatch(list,i){const spec=MATERIAL_SPECS[i];return list.find(asset=>{const text=[asset.id,asset.name,asset.category,...(Array.isArray(asset.tags)?asset.tags:[])].join(" ").toLowerCase().replace(/[_-]/g," ");return spec.terms.every(term=>text.split(/[^a-z]+/).includes(term));})||null;}
async function loadMaterialIndex(){if(materialIndex)return materialIndex;if(materialIndexPromise)return materialIndexPromise;materialIndexPromise=fetch("https://api.polyhaven.com/assets?t=textures",{mode:"cors",signal:AbortSignal.timeout(6500)}).then(r=>{if(!r.ok)throw Error("Nguồn vật liệu tạm thời không khả dụng");return r.json()}).then(data=>{if(!data||typeof data!=="object"||Array.isArray(data))throw Error("Dữ liệu thư viện không hợp lệ");materialIndex=Object.entries(data).filter(([id,x])=>x&&typeof x==="object").map(([id,x])=>({id,...x}));return materialIndex}).finally(()=>{materialIndexPromise=null});return materialIndexPromise;}
function renderLibrary(){shell(header("TRI THỨC VẬT LIỆU","Thư viện vật liệu","Thông số dưới mỗi thẻ mô tả đúng nhóm vật liệu. Mẫu 3D tối giản mô phỏng đặc điểm vật liệu; màu và vân không thay thế mẫu thật. Không lưu ảnh vào mã nguồn hoặc dự án.")+'<div class="notice">Nguồn tham khảo miễn phí CC0: <a href="https://polyhaven.com/textures" target="_blank" rel="noopener noreferrer">Poly Haven ↗</a> · <a href="https://ambientcg.com/list" target="_blank" rel="noopener noreferrer">ambientCG ↗</a>. Từ khóa trùng khớp chưa xác nhận mã thương mại, bề mặt hoàn thiện hay tính chất thi công. <strong>Dữ liệu tham khảo từ Poly Haven</strong> khi xem dữ liệu từ API.</div><div class="grid g4">'+MATERIALS.map((m,i)=>'<div class="mat-card"><div class="swatch material-preview" data-preview="'+i+'" style="background:'+m.color+'"><span class="material-preview-note">Mô phỏng 3D · Màu/vân tham khảo</span></div><span class="eyebrow">'+esc(m.type)+'</span><h3>'+esc(m.name)+'</h3><p class="material-definition">'+esc(m.properties)+'</p><p class="material-application"><b>Ứng dụng:</b> '+esc(m.application)+'</p><p class="material-caution"><b>Lưu ý:</b> '+esc(m.caution)+'</p><div class="button-row"><button class="btn btn-small" data-material="'+i+'">Thêm vào dự án</button><a class="btn btn-small" target="_blank" rel="noopener noreferrer" href="'+materialSearchUrl(i)+'" data-material-link="'+i+'">Tìm đúng loại ↗</a><a class="btn btn-small" target="_blank" rel="noopener noreferrer" href="'+materialAlternateUrl(i)+'">Nguồn khác ↗</a></div><small class="material-source" data-source="'+i+'">Đang tìm mẫu tương đồng…</small></div>').join("")+'</div><div class="section-title"><h2>Vật liệu đã chọn</h2></div><div class="panel">'+((project().data.materials||[]).length?esc(project().data.materials.join(" · ")):'<p>Chưa chọn vật liệu cho dự án này.</p>')+'</div>');view.querySelectorAll("[data-preview]").forEach((box,i)=>materialSample(box,i));loadMaterialPreviews();}
async function loadMaterialPreviews(){const libraryRoot=view.querySelector("[data-preview]");let list;try{list=await loadMaterialIndex()}catch(e){if(libraryRoot?.isConnected)view.querySelectorAll(".material-source").forEach(el=>el.textContent="Không tải được kho trực tuyến · mẫu 3D vẫn hoạt động, dùng nút Tìm đúng loại");return;}if(!libraryRoot?.isConnected||view.querySelector("[data-preview]")!==libraryRoot)return;for(let i=0;i<MATERIALS.length;i++){let box=view.querySelector('[data-preview="'+i+'"]'),source=view.querySelector('[data-source="'+i+'"]');if(!box||!source)continue;const match=materialMatch(list,i);if(!match){source.textContent="Chưa có mẫu xác thực · khối 3D là mô phỏng, xem tìm kiếm chuyên biệt";continue;}const button=view.querySelector('[data-material-link="'+i+'"]');if(button){button.href="https://polyhaven.com/a/"+encodeURIComponent(match.id);button.textContent="Xem mẫu trùng từ khóa ↗";}const tile=box.querySelector(".material-tile");if(tile){tile.style.setProperty("--material-texture",'url("https://cdn.polyhaven.com/asset_img/thumbs/'+encodeURIComponent(match.id)+'.png")');tile.classList.add("has-remote-texture");}const label=box.querySelector(".material-preview-note");if(label)label.textContent="Mô phỏng 3D · Bề mặt Poly Haven tham khảo";source.replaceChildren();let link=document.createElement("a");link.href="https://polyhaven.com/a/"+encodeURIComponent(match.id);link.target="_blank";link.rel="noopener noreferrer";link.textContent="Xem mẫu: "+match.name+" ↗";source.append(link);}}
function renderProjects(){shell(header("QUẢN LÝ DỰ ÁN","Quản lý dự án","Lịch sử, sao lưu, xuất/nhập dự án trên thiết bị. Dữ liệu chưa được đồng bộ đám mây.")+
'<div class="button-row" style="margin-bottom:18px"><button class="btn btn-gold" id="projectCreate">＋ Tạo dự án</button><button class="btn" id="exportAll">↓ Sao lưu toàn bộ</button><button class="btn" id="projectImport">↑ Nhập tệp dự án</button><input id="importFile" type="file" accept=".json,application/json" hidden></div>'+
'<div class="grid g3">'+projects.map(p=>'<div class="project-card"><span class="eyebrow">'+esc(p.space||"Nội thất")+'</span><h3>'+esc(p.name)+'</h3><small>Cập nhật '+esc(new Date(p.updated).toLocaleString("vi-VN"))+'</small><p class="small">'+esc(p.notes||"Chưa có ghi chú")+'</p><div class="button-row"><button class="btn btn-small" data-project="'+esc(p.id)+'">Mở</button><button class="btn btn-small" data-export="'+esc(p.id)+'">Xuất</button><button class="btn btn-small btn-danger" data-delete="'+esc(p.id)+'">Xóa</button></div></div>').join("")+'</div>'+
'<div class="panel" style="margin-top:20px"><h2>Hồ sơ dự án hiện tại</h2>'+field("Tên dự án","projectName",project().name)+field("Ghi chú","notes",project().notes||"")+'<div class="button-row"><button class="btn btn-gold" id="saveProjectMeta">Lưu thông tin</button><button class="btn" id="duplicateProject">Nhân bản phương án</button></div></div>'+
'<div class="notice">Dữ liệu dự án lưu bằng bộ nhớ trình duyệt. Xóa dữ liệu trang web, dùng chế độ riêng tư hoặc đổi máy có thể mất dự án. Hãy tải JSON định kỳ; không lưu ảnh nhạy cảm hoặc bí mật API vào tệp xuất.</div>');}
function renderSystem(){let storage=storeOk?"Khả dụng":"Bị chặn/đầy";let online=navigator.onLine?"Có kết nối":"Ngoại tuyến";shell(header("QUẢN TRỊ HỆ THỐNG","Hệ thống & vận hành","Nhật ký khả năng, trạng thái phân hệ và kiểm tra tài nguyên giao diện tại chỗ.")+
'<div class="grid g3"><div class="stat"><strong>V'+VERSION+'</strong><span>Phiên bản ứng dụng</span></div><div class="stat"><strong>'+esc(storage)+'</strong><span>Bộ nhớ cục bộ</span></div><div class="stat"><strong>'+esc(online)+'</strong><span>Trạng thái mạng</span></div></div>'+
'<div class="section-title"><h2>Kiểm tra hoạt động</h2><button class="btn btn-gold" id="healthCheck">Chạy kiểm tra</button></div><div class="panel" id="healthResult"><p>Chưa chạy kiểm tra tài nguyên trong phiên này. Nút kiểm tra sẽ thử tải những tệp cốt lõi.</p></div>'+
'<div class="section-title"><h2>Đăng ký phân hệ</h2></div><div class="panel">'+MODULES.map(m=>'<div class="module-row"><div class="symbol">'+esc(m.icon)+'</div><div class="description"><b>'+esc(ARTNAME[m.id]||m.vi)+'</b><small>'+esc(m.detail)+'</small></div>'+statusBadge(m.status)+'</div>').join("")+'</div>'+
'<div class="section-title"><h2>Tài nguyên quản trị</h2></div><div class="panel"><p>Triển khai an toàn qua nhánh kiểm thử, kiểm tra hồi quy, xem xét thay đổi và khả năng quay lại phiên bản trước. Chưa có hệ thống tự sửa lỗi website đang chạy.</p><div class="button-row"><a class="btn" href="https://github.com/hoanggiaktsda-beep/hoanggia-studio" target="_blank" rel="noopener">GitHub repository ↗</a><button class="btn" data-route="projects">Sao lưu dự án</button></div></div>');}
function openModule(id){moduleId=id;route="creative";const m=MODULES.find(x=>x.id===id);if(!m)return;let heading=header("HOANGGIA STUDIO / "+(ARTNAME[m.id]||m.vi),ARTNAME[m.id]||m.vi,m.detail,'<button class="btn btn-small" data-route="creative">← Tất cả công cụ</button>');if(EXTERNAL_TOOLS[id]){location.assign(EXTERNAL_TOOLS[id]);return;}else if(id==="vision")renderVision(heading);else if(id==="plan")renderPlan(heading);else if(id==="boq")renderBOQ(heading);else if(id==="material"){renderLibrary();}else if(id==="expert"){renderIntelligence();}else{shell(heading+'<div class="panel"><h2>Chưa kết nối nguồn chính thức</h2><p>Visual AI sẽ chỉ được kích hoạt sau khi xác minh mã nguồn, URL và kiểm tra chức năng thực. Không hiển thị công cụ giả.</p></div>');}document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle("active",b.dataset.route===route));$("#crumb").textContent=(ARTNAME[m.id]||m.vi).toUpperCase();}
function renderPromptLab(head,id){let current=project().data[id]||(id!=="design"?Object.fromEntries(["space","zone","style","brief","place","time","material","light","camera"].filter(k=>project().data.design?.[k]).map(k=>[k,project().data.design[k]])):{});if(!current.material&&(project().data.materials||[]).length)current={...current,material:project().data.materials.join(", ")};const val=(k,def="")=>current[k]??def,form='<div class="workspace"><section class="panel"><h2>01 / Ý định & quyết định</h2><div class="field-row">'+field("Không gian","space",val("space",project().space),SPACES)+field("Khu vực","zone",val("zone","Phòng khách"))+'</div><div class="field-row">'+field("Phong cách","style",val("style","Minimal Luxury"),STYLES)+field("Nhiệm vụ","task",val("task",id==="design"?"create":id==="video"?"edit":"edit"),["create","edit"])+'</div>'+field("Mô tả yêu cầu thiết kế","brief",val("brief"))+'<div class="field-row">'+field("Địa điểm / bối cảnh","place",val("place","Hà Nội, Việt Nam"))+field("Thời gian / mùa","time",val("time","Mùa thu, ban ngày"))+'</div><div class="field-row">'+field("Vật liệu","material",val("material"))+field("Ánh sáng","light",val("light","Natural Daylight"))+'</div><div class="field-row">'+field("Góc máy","camera",val("camera","Eye Level, 35mm"))+field("Giữ kiến trúc / góc máy","preserve",val("preserve",id==="edit"?"yes":"no"),["yes","no"])+'</div>'+
(id==="edit"?'<div class="field-row">'+field("Chuyên gia thực thi","expert",val("expert",EXPERTS[0]),EXPERTS)+field("Có ảnh tham chiếu?","reference",val("reference","no"),["no","yes"])+'</div><div class="notice">Có thể đính kèm ảnh vào ứng dụng Edit AI gốc; Studio chưa truyền ảnh qua website khác hoặc tự phân tích nội dung ảnh.</div>':"")+
(id==="video"?'<div class="field-row">'+field("Số cảnh","shots",val("shots","3"),["1","2","3","4","5","6","8","10"])+field("Chuyển động","motion",val("motion","Slow Dolly"),["Slow Dolly","Orbit","Tracking","Static","Crane","Push In"])+'</div>':"")+
(id==="design"?'<details open class="panel" style="margin:12px 0"><summary><strong>02 / Phân tích công năng & kỹ thuật</strong></summary><p class="notice">Kích thước tính bằng mét, chỉ là dữ liệu nhập; chưa đọc bản vẽ hay xác minh hiện trạng.</p><div class="field-row">'+field("Chiều rộng (m)","width",val("width"))+field("Chiều sâu (m)","depth",val("depth"))+'</div>'+field("Sản phẩm và kích thước","furniture",val("furniture"))+field("Ràng buộc hiện trạng","constraints",val("constraints"))+field("Ưu tiên công năng","designIntent",val("designIntent"))+'</details>':"")+'<div class="button-row"><button class="btn btn-gold" id="makePrompt">Phân tích & tạo prompt</button><button class="btn" id="resetPrompt">Đặt lại</button></div></section>'+
'<section class="panel"><h2>'+(id==="design"?"03":"02")+' / Kết quả & kiểm định</h2><span class="eyebrow">BỘ BIÊN SOẠN YÊU CẦU · THEO QUY TẮC</span><div class="notice">Prompt được tạo bằng bộ quy tắc cục bộ; đây không phải kết quả tạo ảnh/video từ mô hình AI.</div><div id="promptWarnings"></div><pre class="result" id="promptResult">'+esc(current.result||"Điền yêu cầu rồi chọn Phân tích & tạo prompt.")+'</pre><div class="button-row" style="margin-top:13px"><button class="btn btn-gold" id="copyPrompt">Sao chép</button><button class="btn" id="savePromptTxt">Tải TXT</button><button class="btn" data-open="edit">→ Chỉnh sửa</button><button class="btn" data-open="video">→ Video</button>'+(MODULES.find(m=>m.id===id)?.live?'<a class="btn" target="_blank" rel="noopener" href="'+MODULES.find(m=>m.id===id).live+'">Mở ứng dụng gốc ↗</a>':MODULES.find(m=>m.id===id)?.repo?'<a class="btn" target="_blank" rel="noopener" href="'+MODULES.find(m=>m.id===id).repo+'">Kho mã nguồn ↗</a>':"")+'</div></section></div>';
shell(head+form);}
function collectFields(){let o={};view.querySelectorAll('[data-field]').forEach(e=>o[e.dataset.field]=e.value);return o;}
function buildPrompt(){let c={...collectFields(),mode:moduleId,referenceProvided:undefined};let q=promptQuality(c);if(moduleId==="design"){const audit=designAudit(c);q.warnings.push(...audit.warnings);if(audit.warnings.length)q.ok=undefined;}let warningBox=$("#promptWarnings");warningBox.innerHTML=q.warnings.map(w=>'<div class="notice '+(q.canGenerate?'':'bad')+'">'+esc(w)+'</div>').join("");if(!q.canGenerate){notify("Vui lòng sửa các lỗi bắt buộc trước khi tạo prompt.");return;}let result=compilePrompt(c);let d=project().data[moduleId]||{};project().data[moduleId]={...d,...c,result};project().space=c.space;project().history.push({when:new Date().toISOString(),type:moduleId,note:"Biên soạn prompt"});project().history=project().history.slice(-100);touch();$("#promptResult").textContent=result;if(q.ok&&q.warnings.length===0)warningBox.innerHTML='<div class="notice good">✓ Không phát hiện xung đột cơ bản.</div>';notify(q.ok?"Đã tạo và lưu prompt.":"Đã tạo bản nháp với cảnh báo cần xem xét.");}
function renderVision(head){shell(head+'<div class="workspace"><section class="panel"><h2>Phân tích ảnh tại thiết bị</h2><p>Thông số ảnh được đo bằng Canvas trên trình duyệt. Không có mô hình thị giác nhận diện sofa, tường, vật liệu hoặc công trình ở phiên bản này.</p><label for="visionFile">Chọn ảnh để phân tích</label><input id="visionFile" type="file" accept="image/png,image/jpeg,image/webp"><div id="visionPreview"></div><button class="btn btn-gold" id="analyzeVision" style="margin-top:12px">Phân tích điểm ảnh</button></section><section class="panel"><h2>Kết quả quan sát</h2><div id="visionResult" class="result">Chưa có ảnh.</div><div class="notice">Không suy đoán vật thể, kích thước thực hoặc chất liệu từ thống kê điểm ảnh.</div></section></div>');}
async function loadImage(file){if(!file||!file.type.startsWith("image/"))throw Error("Tệp không phải định dạng ảnh hỗ trợ.");if(file.size>35*1024*1024)throw Error("Ảnh vượt 35 MB.");if(typeof createImageBitmap==="function")return createImageBitmap(file);return new Promise((resolve,reject)=>{let url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error("Không đọc được ảnh."))};img.src=url;});}
async function runVision(){if(!visionFile){notify("Vui lòng chọn ảnh.");return;}try{let img=await loadImage(visionFile),w=img.width,h=img.height;if(!w||!h)throw Error("Kích thước ảnh không hợp lệ.");let cv=document.createElement("canvas");cv.width=64;cv.height=64;let cx=cv.getContext("2d",{willReadFrequently:true});cx.drawImage(img,0,0,64,64);let data=cx.getImageData(0,0,64,64).data,r=0,g=0,b=0,lum=0,lum2=0;for(let i=0;i<data.length;i+=4){r+=data[i];g+=data[i+1];b+=data[i+2];let y=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];lum+=y;lum2+=y*y;}let n=data.length/4;let avg=Math.round(lum/n),contrast=Math.round(Math.sqrt(Math.max(0,lum2/n-(lum/n)**2)));let txt="Tệp: "+visionFile.name+"\nKích thước: "+w+" × "+h+" px\nTỷ lệ: "+(w/h).toFixed(3)+"\nĐộ phân giải: "+(w*h/1e6).toFixed(2)+" MP\nMàu trung bình (RGB): "+[r,g,b].map(x=>Math.round(x/n)).join(", ")+"\nĐộ sáng trung bình: "+avg+"/255\nĐộ lệch chuẩn độ sáng: "+contrast+"\n\nChưa thực hiện nhận diện vật thể hoặc kích thước thực.";$("#visionResult").textContent=txt;visionData={name:visionFile.name,w,h,brightness:avg,contrast};project().data.vision=visionData;touch();if(typeof img.close==="function")img.close();notify("Đã phân tích thông số ảnh.");}catch(e){notify(e.message);}}
function renderUpscale(head){shell(head+'<div class="workspace"><section class="panel"><h2>01 / Tải ảnh</h2><input id="upscaleFile" aria-label="Ảnh gốc" type="file" accept="image/png,image/jpeg,image/webp"><div id="upscalePreview"></div><div class="field-row"><div class="field"><label for="scale">Hệ số kích thước</label><select id="scale"><option value="2">2×</option><option value="3">3×</option><option value="4">4×</option></select></div><div class="field"><label for="smooth">Nội suy</label><select id="smooth"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div></div><div class="notice">Công cụ này dùng nội suy Canvas để tăng số pixel, không phải AI super-resolution và không tái tạo chi tiết thực bị thiếu.</div><button class="btn btn-gold" id="processUpscale">Tạo ảnh kích thước lớn</button></section><section class="panel"><h2>02 / Kết quả</h2><div id="upscaleResult">Chưa xử lý.</div></section></div>');}
async function doUpscale(){if(!upscaleFile){notify("Vui lòng tải ảnh.");return;}let button=$("#processUpscale");button.disabled=true;button.textContent="Đang xử lý...";try{let img=await loadImage(upscaleFile),s=Number($("#scale").value),w=img.width*s,h=img.height*s;if(w*h>24000000||w>8192||h>8192)throw Error("Ảnh sau phóng vượt giới hạn 24 MP hoặc chiều cạnh 8192 px.");let cv=document.createElement("canvas");cv.width=w;cv.height=h;let ctx=cv.getContext("2d");if(!ctx)throw Error("Không tạo được bộ xử lý Canvas.");ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality=$("#smooth").value;ctx.drawImage(img,0,0,w,h);let blob=await new Promise((ok,no)=>cv.toBlob(v=>v?ok(v):no(Error("Xuất ảnh thất bại.")),"image/png"));if(upscaleUrl)URL.revokeObjectURL(upscaleUrl);upscaleUrl=URL.createObjectURL(blob);$("#upscaleResult").innerHTML='<p>Đã xử lý: '+w+' × '+h+' px · '+(blob.size/1024/1024).toFixed(1)+' MB</p><img class="file-preview" id="upscaledPreview" alt="Ảnh nội suy kết quả"><div class="button-row"><a class="btn btn-gold" id="upscaledDownload" download="HG-upscaled.png">↓ Tải PNG</a></div>';$("#upscaledPreview").src=upscaleUrl;$("#upscaledDownload").href=upscaleUrl;cv.width=cv.height=1;if(typeof img.close==="function")img.close();notify("Đã nội suy ảnh.");}catch(e){notify(e.message);}finally{button.disabled=undefined;button.textContent="Tạo ảnh kích thước lớn";}}
function renderPlan(head){let d=project().data.plan||{};shell(head+'<div class="workspace"><section class="panel"><h2>Đo diện tích theo kích thước nhập</h2><p>Đo thủ công (m). Không tự đọc DWG, PDF hoặc nhận diện kích thước bản vẽ.</p>'+field("Tên khu vực","zone",d.zone||"Phòng khách")+'<div class="field-row"><div class="field"><label for="widthM">Chiều dài (m)</label><input id="widthM" type="number" min=".01" max="100000" step=".01" value="'+esc(d.w||"")+'"></div><div class="field"><label for="heightM">Chiều rộng (m)</label><input id="heightM" type="number" min=".01" max="100000" step=".01" value="'+esc(d.h||"")+'"></div></div><button class="btn btn-gold" id="computeArea">Tính diện tích</button></section><section class="panel"><h2>Diện tích</h2><div class="result" id="areaResult">'+esc(d.result||"Nhập chiều dài và chiều rộng để tính diện tích hình chữ nhật.")+'</div><div class="notice">Mặt bằng có hình dạng phức tạp phải chia khu đo hoặc dùng bản vẽ có kích thước kiểm chứng.</div></section></div>');}
function renderBOQ(head){let rows=project().data.boq||[{name:"",unit:"m²",qty:"",price:""}];const trs=rows.map((r,i)=>'<tr><td><input data-i="'+i+'" data-k="name" aria-label="Hạng mục '+(i+1)+'" value="'+esc(r.name||"")+'"></td><td><input data-i="'+i+'" data-k="unit" aria-label="Đơn vị '+(i+1)+'" value="'+esc(r.unit||"")+'"></td><td><input data-i="'+i+'" data-k="qty" type="number" min="0" aria-label="Khối lượng '+(i+1)+'" value="'+esc(r.qty??"")+'"></td><td><input data-i="'+i+'" data-k="price" type="number" min="0" aria-label="Đơn giá '+(i+1)+'" value="'+esc(r.price??"")+'"></td><td class="num">'+formatVnd((Number(r.qty)||0)*(Number(r.price)||0))+'</td><td><button class="btn btn-small btn-danger" data-remove-row="'+i+'" aria-label="Xóa dòng '+(i+1)+'">×</button></td></tr>').join("");
shell(head+'<div class="panel"><h2>Dự toán theo dữ liệu nhập</h2><div class="notice">Không tự động lấy đơn giá thị trường hoặc xác định khối lượng từ ảnh. Giá và khối lượng chỉ do người dùng cung cấp; kết quả chưa gồm thuế, hao hụt hoặc dự phòng.</div><div class="data-scroll"><table class="data-table"><thead><tr><th>Hạng mục</th><th>Đơn vị</th><th>Khối lượng</th><th>Đơn giá (₫)</th><th>Thành tiền</th><th></th></tr></thead><tbody>'+trs+'</tbody></table></div><div class="right" style="margin:17px 0"><strong id="boqTotal">Tổng: '+formatVnd(boq(rows).total)+'</strong></div><div class="button-row"><button class="btn btn-gold" id="addBoqRow">＋ Hạng mục</button><button class="btn" id="calcBoq">Tính & lưu</button><button class="btn" id="exportBoq">↓ Xuất CSV</button></div></div>');}
function navigate(next){route=next;let hash="#"+next;if(location.hash!==hash)history.replaceState(null,"",hash);if(next==="home")renderHome();else if(next==="creative")renderCreative();else if(next==="intelligence")renderIntelligence();else if(next==="library")renderLibrary();else if(next==="projects")renderProjects();else renderSystem();window.scrollTo(0,0);}
async function runHealth(){let box=$("#healthResult");box.innerHTML="<p>Đang xác minh tài nguyên...</p>";let results=[];for(let path of ["./index.html","./styles.css","./src/core.js","./src/app.js","./assets/icon.svg","./manifest.webmanifest"]){try{let r=await fetch(path,{cache:"no-store"});results.push({path,ok:r.ok,status:r.status});}catch(e){results.push({path,ok:undefined,status:"Không truy cập"});}}let success=results.every(x=>x.ok);box.innerHTML=results.map(x=>'<div class="health-row"><b>'+esc(x.path)+'</b><span>'+esc(x.status)+'</span><span class="pill '+(x.ok?"":"limit")+'">'+(x.ok?"ĐẠT":"LỖI")+'</span></div>').join("")+'<div class="notice '+(success?"good":"bad")+'">'+(success?"Tải được 6/6 tệp.":"Một số tài nguyên tải thất bại.")+' Đây chỉ là kiểm tra tài nguyên, chưa thay thế kiểm thử trình duyệt thực tế và các AI khác.</div>';notify(success?"Tài nguyên cơ bản khả dụng.":"Có lỗi tài nguyên cần xem lại.");}
function makeProject(){let n=prompt("Tên dự án mới","Dự án kiến trúc mới");if(n===null)return;n=safeText(n,120)||"Dự án mới";let p=newProject(n);projects.unshift(p);active=p.id;save();navigate("projects");notify("Đã tạo dự án.");}
function importProject(file){if(!file)return;if(file.size>5*1024*1024){notify("Tệp JSON vượt 5MB.");return;}file.text().then(txt=>{let obj=JSON.parse(txt);let arr=Array.isArray(obj)?obj:[obj];if(!arr.length||arr.length>80||!arr.every(validateProject))throw Error("Định dạng dự án không hợp lệ.");let imported=arr.map(p=>({...p,id:"hg-"+Date.now()+"-"+Math.random().toString(36).slice(2,7),name:safeText(p.name,120),notes:safeText(p.notes,5000),updated:new Date().toISOString(),history:p.history.slice(-100)}));if(projects.length+imported.length>80)throw Error("Quá giới hạn 80 dự án.");projects.push(...imported);active=imported[0].id;save();navigate("projects");notify("Đã nhập "+imported.length+" dự án.");}).catch(e=>notify(e.message));}
function prepareInputPreview(file,target){if(!file)return;let box=$(target);if(!box)return;let img=document.createElement("img");img.className="file-preview";img.alt="Xem trước ảnh tải lên";let url=URL.createObjectURL(file);img.onload=()=>URL.revokeObjectURL(url);img.onerror=()=>URL.revokeObjectURL(url);img.src=url;box.replaceChildren(img);}
function action(e){const t=e.target.closest("button,a");if(!t)return;
if(t.dataset.route){e.preventDefault();navigate(t.dataset.route);return;}
if(t.dataset.open){if(EXTERNAL_TOOLS[t.dataset.open]){location.assign(EXTERNAL_TOOLS[t.dataset.open]);return;}openModule(t.dataset.open);return;}
if(t.dataset.project){active=t.dataset.project;save();navigate("projects");return;}
if(t.dataset.material){let m=MATERIALS[Number(t.dataset.material)];if(m){project().data.materials=[...new Set([...(project().data.materials||[]),m.name])];touch();navigate("library");notify("Đã chọn "+m.name);}return;}
if(t.dataset.export){let p=projects.find(x=>x.id===t.dataset.export);if(p)download(JSON.stringify(p,null,2),"HOANGGIA-"+p.id+".json","application/json");return;}
if(t.dataset.delete){if(projects.length<=1){notify("Cần giữ ít nhất một dự án.");return;}let p=projects.find(x=>x.id===t.dataset.delete);if(confirm("Xóa dự án “"+p.name+"”? Không thể hoàn tác nếu chưa sao lưu.")){projects=projects.filter(x=>x!==p);if(active===p.id)active=projects[0].id;save();renderProjects();}return;}
switch(t.id){
case "newProject":case "projectCreate":makeProject();break;
case "makePrompt":buildPrompt();break;
case "resetPrompt":if(confirm("Xóa biểu mẫu hiện tại?")){delete project().data[moduleId];touch();openModule(moduleId);}break;
case "copyPrompt":{let s=$("#promptResult")?.textContent||"";if(!s||s.startsWith("Điền"))return notify("Chưa có prompt.");if(!navigator.clipboard?.writeText){notify("Trình duyệt không hỗ trợ sao chép tự động. Hãy tải TXT.");break;}navigator.clipboard.writeText(s).then(()=>notify("Đã sao chép."),()=>notify("Không sao chép được; dùng tải TXT."));break;}
case "savePromptTxt":{let s=$("#promptResult")?.textContent||"";if(s&&!s.startsWith("Điền"))download(s,"HOANGGIA-"+moduleId+".txt");break;}
case "analyzeVision":runVision();break;
case "processUpscale":doUpscale();break;
case "computeArea":{let w=$("#widthM").value,h=$("#heightM").value,a=area(w,h);if(a===null)return notify("Chiều dài/rộng phải dương và hợp lệ.");let zone=view.querySelector('[data-field="zone"]').value;let txt="Khu vực: "+zone+"\nDài: "+w+" m · Rộng: "+h+" m\nDiện tích: "+a.toLocaleString("vi-VN")+" m²\nGiả định: hình chữ nhật, số đo do người dùng cung cấp.";$("#areaResult").textContent=txt;project().data.plan={zone,w,h,result:txt};touch();break;}
case "addBoqRow":{let rows=project().data.boq||[];rows.push({name:"",unit:"m²",qty:"",price:""});project().data.boq=rows;touch();renderBOQ(header("KỸ THUẬT","BOQ AI","Dự toán theo dữ liệu nhập"));break;}
case "calcBoq":{const rows=readBOQ();let result=boq(rows);project().data.boq=rows;touch();$("#boqTotal").textContent="Tổng: "+formatVnd(result.total);notify("Đã tính và lưu "+result.rows.length+" hạng mục hợp lệ.");break;}
case "exportBoq":{let r=boq(readBOQ()).rows;download("\ufeff"+csv([["Hạng mục","Đơn vị","Khối lượng","Đơn giá (VND)","Thành tiền (VND)"],...r.map(x=>[x.name,x.unit,x.qty,x.price,x.cost])]),"HG-BOQ.csv","text/csv;charset=utf-8");break;}
case "exportAll":download(JSON.stringify(projects,null,2),"HOANGGIA-STUDIO-BACKUP.json","application/json");break;
case "projectImport":$("#importFile").click();break;
case "saveProjectMeta":project().name=safeText(view.querySelector('[data-field="projectName"]').value,120)||"Dự án";project().notes=safeText(view.querySelector('[data-field="notes"]').value,5000);touch();navigate("projects");notify("Đã lưu hồ sơ.");break;
case "duplicateProject":{let p=structuredClone(project());p.id=newProject().id;p.name=p.name+" — Phương án mới";p.created=new Date().toISOString();p.updated=p.created;projects.unshift(p);active=p.id;save();renderProjects();break;}
case "healthCheck":runHealth();break;
}}
function readBOQ(){let rows=[];view.querySelectorAll("tbody tr").forEach(tr=>{let r={};tr.querySelectorAll("[data-k]").forEach(el=>r[el.dataset.k]=el.value);rows.push(r);});return rows;}
function handleClick(e){if(e.target.matches("[data-remove-row]")){let i=Number(e.target.dataset.removeRow),rows=readBOQ();rows.splice(i,1);project().data.boq=rows;touch();renderBOQ(header("KỸ THUẬT","BOQ AI","Dự toán theo dữ liệu nhập"));return;}action(e);}
view.addEventListener("click",handleClick);
view.addEventListener("change",e=>{if(e.target.id==="visionFile"){visionFile=e.target.files?.[0]||null;prepareInputPreview(visionFile,"#visionPreview");}if(e.target.id==="upscaleFile"){upscaleFile=e.target.files?.[0]||null;prepareInputPreview(upscaleFile,"#upscalePreview");}if(e.target.id==="importFile")importProject(e.target.files?.[0]);});
document.querySelector(".topbar").addEventListener("click",action);document.querySelector(".side").addEventListener("click",action);document.querySelector(".mobile-nav").addEventListener("click",action);
$("#projectSelect").addEventListener("change",e=>{active=e.target.value;save();navigate(route);});
window.addEventListener("hashchange",()=>{let r=location.hash.replace("#","");if(["home","creative","intelligence","library","projects","system"].includes(r))navigate(r);});
window.addEventListener("error",e=>{console.error("HOANGGIA STUDIO runtime:",e.message);});
window.addEventListener("unhandledrejection",e=>{console.error("HOANGGIA STUDIO promise:",e.reason);});
seed();navigate(["home","creative","intelligence","library","projects","system"].includes(location.hash.slice(1))?location.hash.slice(1):"home");
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(e=>console.warn("PWA:",e.message)));
