import {designReview,designAudit} from "./design-brain.js";
import {resolveDepartment} from "./intelligence-core.js";
/* HOANGGIA STUDIO — reusable deterministic intelligence layer. No external API or fake model inference. */
export const VERSION="3.0.0";
export const MODULES=[
{id:"design",label:"Design AI",vi:"Thiết kế không gian",group:"creative",icon:"◈",status:"local",repo:"https://github.com/hoanggiaktsda-beep/da-studio",live:"https://hoanggiaktsda-beep.github.io/da-studio/",detail:"Biên soạn định hướng kiến trúc, nội thất, quy hoạch, cảnh quan"},
{id:"edit",label:"Edit AI",vi:"Chỉnh sửa & đồng bộ",group:"creative",icon:"▧",status:"local",repo:"https://github.com/hoanggiaktsda-beep/hoanggia-studioai",live:"https://hoanggiaktsda-beep.github.io/hoanggia-studioai/",detail:"ReferenceReplica, SpaceSync, khóa kiến trúc và góc máy"},
{id:"video",label:"Video AI",vi:"Kịch bản & camera",group:"creative",icon:"▷",status:"local",repo:"https://github.com/hoanggiaktsda-beep/prompt-ai-videos",live:"https://hoanggiaktsda-beep.github.io/prompt-ai-videos/",detail:"Shot sequence, nhân vật, ánh sáng và chuyển động"},
{id:"upscale",label:"Upscale AI",vi:"Nâng cấp ảnh",group:"creative",icon:"⬡",status:"local",repo:"https://github.com/hoanggiaktsda-beep/HG-UPSCALE-AI",live:"https://hoanggiaktsda-beep.github.io/HG-UPSCALE-AI/",detail:"Phóng ảnh trên trình duyệt, không tự nhận là AI siêu phân giải"},
{id:"visual",label:"Visual AI",vi:"Trực quan hóa",group:"creative",icon:"◇",status:"planned",detail:"Chưa xác minh ứng dụng nguồn để kết nối"},
{id:"plan",label:"Plan AI",vi:"Phân tích diện tích",group:"technical",icon:"▤",status:"local",detail:"Dữ liệu đo nhập thủ công, tính diện tích cơ bản"},
{id:"material",label:"Material AI",vi:"Thư viện vật liệu",group:"technical",icon:"▦",status:"local",detail:"Bảng vật liệu tham chiếu, không phải dữ liệu nhà cung cấp"},
{id:"boq",label:"BOQ AI",vi:"Khối lượng & dự toán",group:"technical",icon:"≡",status:"local",detail:"Dự toán theo số liệu và đơn giá do người dùng nhập"},
{id:"vision",label:"HG Vision",vi:"Đọc thông số ảnh",group:"intelligence",icon:"◎",status:"limited",detail:"Phân tích điểm ảnh và màu sắc, chưa có nhận diện đối tượng bằng mô hình thị giác"},
{id:"expert",label:"HG Expert Brain",vi:"Bộ não chuyên gia",group:"intelligence",icon:"✳",status:"local",detail:"Quy tắc thiết kế và kiểm soát mâu thuẫn điều kiện"}];
export const SPACES=["Nội thất","Kiến trúc","Quy hoạch","Cảnh quan"];
export const STYLES=["Minimal Luxury","Contemporary","Modern","Neo Classic","Wabi-Sabi","Japandi","Luxury","Bauhaus","Biophilic","Tropical Coastal","Industrial","Classic"];
export const EXPERTS=["Nội thất / Citterio","Vật liệu / Zumthor","Ánh sáng / Ingo Maurer","Góc máy / Iwan Baan","Loại bỏ đối tượng","Tỷ lệ khung hình","Tái tạo theo ảnh tham chiếu","Đồng bộ không gian","Kịch bản phân cảnh"];
export const MATERIALS=[
{name:"Travertine",type:"ĐÁ TRAVERTINE · ĐÁ VÔI",color:"#b9ab91",properties:"Đá vôi tự nhiên màu kem–be, có lỗ rỗng và vân phân lớp; bề mặt có thể trám lỗ, mài honed hoặc đánh bóng.",application:"Ốp tường, sàn, bàn và chi tiết trang trí.",caution:"Kiểm tra độ hút nước, khả năng chống ố và mẫu tấm thực tế."},
{name:"Calacatta",type:"ĐÁ MARBLE · CALACATTA",color:"#e2ddd0",properties:"Marble nền trắng sáng, vân lớn màu xám hoặc vàng; Calacatta là nhóm đá có nhiều biến thể, không phải mọi marble trắng.",application:"Mặt bàn, vách điểm nhấn, sàn và phòng tắm.",caution:"Kiểm tra nguồn đá, vân theo slab, chống axit và chống thấm."},
{name:"Oak Veneer",type:"GỖ LẠNG · VENEER SỒI",color:"#a78761",properties:"Lớp gỗ sồi tự nhiên lạng mỏng phủ lên cốt ván; vân thẳng hoặc núi, màu vàng nhạt đến nâu mật ong.",application:"Cánh tủ, ốp vách, nội thất gỗ và cửa.",caution:"Chỉ định cốt ván, chiều vân, độ dày veneer và lớp sơn phủ."},
{name:"Walnut",type:"GỖ LẠNG · VENEER ÓC CHÓ",color:"#634736",properties:"Veneer óc chó có nền nâu chocolate đến nâu tím, vân sọc hoặc cuộn; không đồng nhất với veneer sồi nhuộm nâu.",application:"Tủ áo, vách trang trí, bàn và hệ nội thất.",caution:"Kiểm tra mẫu veneer thật, ghép vân và sai lệch màu theo lô."},
{name:"Brushed Brass",type:"KIM LOẠI · ĐỒNG XƯỚC",color:"#ae9568",properties:"Bề mặt màu đồng vàng có các đường xước mịn theo một hướng; có thể là đồng thật hoặc thép phủ màu đồng.",application:"Nẹp, tay nắm, khung trang trí và chân bàn.",caution:"Phân biệt vật liệu nền, phương pháp mạ/PVD, lớp bảo vệ và chống oxy hóa."},
{name:"Saddle Leather",type:"DA · DA YÊN NGỰA",color:"#795743",properties:"Da thuộc tương đối dày, giữ phom, bề mặt có hạt hoặc mịn, thường có sắc nâu ấm; không đồng nghĩa với mọi loại da màu nâu.",application:"Bọc ghế, đầu giường, tay nắm và ốp trang trí.",caution:"Kiểm tra da thật hay nhân tạo, độ dày, hoàn thiện và độ bền màu."},
{name:"Linen",type:"VẢI · LANH TỰ NHIÊN",color:"#c9c0aa",properties:"Vải từ sợi lanh có thớ dệt rõ, bề mặt mộc, thoáng và dễ nhăn; có thể pha cotton hoặc polyester.",application:"Rèm, vải bọc ghế, gối và phụ kiện.",caution:"Xác minh thành phần sợi, độ co rút, độ bền mài mòn và khả năng vệ sinh."},
{name:"Smoked Glass",type:"KÍNH · KÍNH MÀU KHÓI",color:"#66716a",properties:"Kính có sắc xám khói hoặc nâu khói, vẫn cho ánh sáng truyền qua; khác kính trong, kính mờ phun cát và gương màu.",application:"Cánh tủ, vách kính, mặt bàn và kệ trưng bày.",caution:"Xác định kính cường lực/dán an toàn, độ dày, màu và độ truyền sáng."}
];
export function newProject(name="Dự án không tên"){return {schemaVersion:1,id:"hg-"+Date.now()+"-"+Math.random().toString(36).slice(2,7),name,space:"Nội thất",created:new Date().toISOString(),updated:new Date().toISOString(),notes:"",data:{},history:[]};}
export function safeText(s,max=5000){return String(s??"").replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max);}
export function validateProject(p){return !!p&&typeof p==="object"&&p.schemaVersion===1&&typeof p.id==="string"&&p.id.length<=100&&typeof p.name==="string"&&p.name.length<=200&&!!p.data&&typeof p.data==="object"&&!Array.isArray(p.data)&&Array.isArray(p.history)&&p.history.length<=200;}
export function area(w,h){let a=Number(w),b=Number(h);if(!Number.isFinite(a)||!Number.isFinite(b)||a<=0||b<=0||a>100000||b>100000)return null;return Math.round(a*b*100)/100;}
export function boq(rows){let out=[],total=0;for(const x of rows){let q=Number(x.qty),p=Number(x.price);if(!x.name||!Number.isFinite(q)||!Number.isFinite(p)||q<0||p<0||q>1e9||p>1e15)continue;let cost=q*p;if(!Number.isFinite(cost))continue;total+=cost;out.push({...x,qty:q,price:p,cost});}return{rows:out,total};}
export function promptQuality(c={}){const warnings=[],errors=[];const mode=c.mode||"design";if(!safeText(c.brief))errors.push("Thiếu mô tả thiết kế.");if(c.preserve==="yes"&&c.task==="create")errors.push("Tạo mới và giữ nguyên kiến trúc: cần làm rõ ảnh gốc hoặc đổi nhiệm vụ.");if(c.reference==="yes"&&!c.referenceProvided)warnings.push("Đang yêu cầu tham chiếu nhưng chưa xác nhận có ảnh tham chiếu.");if(mode==="video"&&(!c.shots||!Number.isInteger(Number(c.shots))||Number(c.shots)<1||Number(c.shots)>30))errors.push("Số cảnh quay không hợp lệ.");return {ok:errors.length===0&&warnings.length===0,canGenerate:errors.length===0,errors,warnings:[...errors,...warnings]};}
export function compilePrompt(c){const policy=resolveDepartment(c.mode||"design",({"Nội thất":"interior","Kiến trúc":"architecture","Quy hoạch":"urban","Cảnh quan":"landscape"}[c.space]||"interior"));const v=x=>safeText(x,1200);const lines=["HOANGGIA STUDIO V3.0 — "+(c.mode==="video"?"ĐẠO DIỄN VIDEO":c.mode==="edit"?"CHỈNH SỬA HÌNH ẢNH":"TRÍ TUỆ THIẾT KẾ"),"Nhiệm vụ: "+(c.task==="create"?"Tạo phương án thiết kế":c.mode==="video"?"Lập chuỗi cảnh":"Chỉnh sửa / đồng bộ")+".","Không gian: "+v(c.space||"Nội thất")+(c.zone?" — "+v(c.zone):"")+".","Phong cách: "+v(c.style||"Contemporary")+"."];if(c.place)lines.push("Địa điểm / bối cảnh: "+v(c.place)+".");if(c.time)lines.push("Thời gian: "+v(c.time)+".");if(c.brief)lines.push("Ý định thiết kế: "+v(c.brief)+".");if(c.material)lines.push("Vật liệu: "+v(c.material)+".");if(c.light)lines.push("Ánh sáng: "+v(c.light)+".");if(c.camera)lines.push("Camera: "+v(c.camera)+".");if(c.mode==="edit"||c.preserve==="yes")lines.push("Ràng buộc: giữ nguyên hình học kiến trúc, bố cục mặt bằng, vị trí camera và phối cảnh; chỉ thay đổi phạm vi được chỉ định.");if(c.mode==="edit"&&c.expert)lines.push("Quyết định chuyên gia: "+v(c.expert)+".");if(c.mode==="video"){lines.push("Số cảnh: "+v(c.shots||"3")+".");lines.push("Chuyển động: "+v(c.motion||"Chậm, ổn định")+".");lines.push("Giữ liên tục nhận diện không gian, sản phẩm, nhân vật và ánh sáng giữa các shot.");}if(c.mode==="design"){const review=designReview(c),audit=designAudit(c);if(audit.area!==null)lines.push("Diện tích hình chữ nhật theo kích thước nhập: "+audit.area+" m² (chưa xác minh hiện trạng).");if(c.furniture)lines.push("Sản phẩm và kích thước do người dùng cung cấp: "+v(c.furniture)+".");if(c.constraints)lines.push("Ràng buộc hiện trạng: "+v(c.constraints)+".");if(c.designIntent)lines.push("Ưu tiên công năng: "+v(c.designIntent)+".");audit.warnings.forEach(x=>lines.push("Cần bổ sung: "+x));lines.push("Kiểm định chuyên ngành "+review.space+": "+review.checks.join("; ")+".");if(review.requiresMeasurements)lines.push("Chưa xác minh kích thước thực tế; không coi số đo suy đoán là thông số thi công.");if(review.requiresSiteVerification)lines.push("Điều kiện hiện trường và quy chuẩn áp dụng cần được kiểm chứng.");}if(policy){lines.push("Bộ não chủ trì: "+policy.lead+".");lines.push("Quy tắc ưu tiên: "+policy.locks.join(", ")+".");if(c.mode==="video")lines.push("Video kiến trúc/nội thất: bảo toàn thiết kế không gian trước kỹ thuật dựng phim.");}lines.push("Yêu cầu: nhất quán tỷ lệ, công năng, vật liệu, ánh sáng vật lý, phối cảnh; không tự tạo chi tiết kiến trúc không được cung cấp.","Chỉ mô tả theo dữ liệu đầu vào; thông số chưa xác minh phải đánh dấu giả định.");return lines.join("\n");}
export function csv(rows){return rows.map(row=>row.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(",")).join("\r\n");}
export function formatVnd(n){return Number(n||0).toLocaleString("vi-VN")+" ₫";}
