/* THƯ KÝ AI — trợ lý cục bộ miễn phí, not a generative AI or Google API integration. */
(()=>{
"use strict";
const KEY="hg-studio-ai-secretary-chat-v2",MAX=45;
const root=document.createElement("section");root.className="mo-companion";root.setAttribute("aria-label","Thư ký AI — trợ lý Studio");
root.innerHTML="<button id=\"moToggle\" class=\"mo-toggle\" type=\"button\" aria-label=\"Mở trò chuyện với Thư ký AI\" aria-expanded=\"false\"><img class=\"mo-portrait mo-toggle-photo\" src=\"./assets/icon.svg\" onerror=\"this.onerror=null;this.src=\u0027https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format%26fit=crop%26w=600%26q=85\u0027\" alt=\"\" loading=\"lazy\"><span class=\"mo-toggle-copy\"><strong>Thư ký AI ♡</strong><small>Trợ lý Studio · Miễn phí</small></span><span class=\"mo-status-dot\" aria-hidden=\"true\"></span></button><div id=\"moPanel\" class=\"mo-panel\" hidden><header class=\"mo-head\"><img class=\"mo-portrait mo-head-photo\" src=\"./assets/icon.svg\" onerror=\"this.onerror=null;this.src=\u0027https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format%26fit=crop%26w=600%26q=85\u0027\" alt=\"\" loading=\"lazy\"><div class=\"mo-heading\"><strong>Thư ký AI ♡</strong><small>Trợ lý Studio · Miễn phí</small><span class=\"mo-online\"><i></i> Sẵn sàng hỗ trợ</span></div><div class=\"mo-head-actions\"><button id=\"moMin\" type=\"button\" title=\"Thu nhỏ\" aria-label=\"Thu nhỏ chat\">−</button><button id=\"moClear\" type=\"button\" title=\"Xóa lịch sử\" aria-label=\"Xóa lịch sử chat\">↻</button><button id=\"moClose\" type=\"button\" aria-label=\"Đóng chat\">×</button></div></header><div class=\"mo-intro\"><div><strong>Thiết kế đẹp hơn khi có người đồng hành.</strong><small>HOANGGIA STUDIO / TRỢ LÝ THIẾT KẾ</small></div></div><div class=\"mo-disclosure\">Trợ lý hướng dẫn theo kịch bản, chưa phải AI hội thoại. Google được mở trong tab mới.</div><div id=\"moMessages\" class=\"mo-messages\" role=\"log\" aria-live=\"polite\" aria-label=\"Lịch sử trò chuyện\"></div><nav class=\"mo-chips\" aria-label=\"Hỗ trợ nhanh\"><button type=\"button\" data-mo-quick=\"Cách tạo dự án\">▧ Hướng dẫn sử dụng</button><button type=\"button\" data-mo-quick=\"Hướng dẫn Design AI\">✎ Ý tưởng thiết kế</button><button type=\"button\" data-mo-quick=\"Tìm kiếm trên Google\">⌕ Google</button><button type=\"button\" data-mo-quick=\"Giải thích thuật ngữ\">▤ Thuật ngữ</button><button type=\"button\" data-mo-quick=\"Gợi ý phong cách\">✧ Phong cách</button></nav><div class=\"mo-suggestions\"><button type=\"button\" data-mo-quick=\"tìm xu hướng nội thất 2026\">◎ Tìm trên Google</button><button type=\"button\" data-mo-quick=\"Gợi ý phong cách\">✧ Gợi ý chi tiết</button></div><form id=\"moForm\" class=\"mo-form\"><label class=\"mo-sr\" for=\"moInput\">Tin nhắn</label><input id=\"moInput\" type=\"text\" maxlength=\"350\" autocomplete=\"off\" placeholder=\"Hỏi tôi hoặc tìm trên Google...\" required><button type=\"submit\" aria-label=\"Gửi tin nhắn\">➤</button></form><p class=\"mo-note\">Thư ký AI hỗ trợ bạn trong thiết kế và sáng tạo · Lưu trên thiết bị</p></div>";
document.body.append(root);
const toggle=root.querySelector("#moToggle"),panel=root.querySelector("#moPanel"),log=root.querySelector("#moMessages"),input=root.querySelector("#moInput");
const safeLoad=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v.filter(x=>x&&["user","mo"].includes(x.role)&&typeof x.text==="string").slice(-MAX):[]}catch{return []}};
let history=safeLoad();if(!history.length)history=[{role:"mo",text:"Xin chào, bạn cần tìm thông tin hay hướng dẫn dùng HOANGGIA STUDIO? Thư ký AI hỗ trợ các thao tác cơ bản và mở Google để tra cứu nhé "}];
function save(){try{localStorage.setItem(KEY,JSON.stringify(history.slice(-MAX)))}catch{}}
function draw(){log.replaceChildren();for(const msg of history){const p=document.createElement("p");p.className="mo-bubble "+msg.role;p.textContent=msg.text;if(msg.role==="user"){const avatar=document.createElement("img");avatar.className="mo-user-avatar";avatar.src="./assets/icon.svg";avatar.alt="HOANGGIA AI";const line=document.createElement("div");line.className="mo-user-line";line.append(p,avatar);log.append(line)}else{log.append(p)}}log.scrollTop=log.scrollHeight}
function say(role,text){history.push({role,text});history=history.slice(-MAX);save();draw()}
function open(state){panel.hidden=!state;toggle.setAttribute("aria-expanded",String(state));toggle.setAttribute("aria-label",state?"Thu gọn trò chuyện với Thư ký AI":"Mở trò chuyện với Thư ký AI");if(state){draw();input.focus()}}
function search(q){const query=q.trim().slice(0,250);if(!query){say("mo","Bạn nhập từ khóa sau “tìm” nhé, ví dụ: tìm vật liệu travertine.");return}const url="https://www.google.com/search?q="+encodeURIComponent(query);const w=window.open(url,"_blank","noopener,noreferrer");say("mo",w?"Thư ký AI đã mở Google với từ khóa: “"+query+"”. Thư ký AI chưa tự đọc nội dung trang kết quả nhé.":"Trình duyệt có thể đã chặn tab mới. Hãy cho phép mở cửa sổ bật lên rồi thử lại.")}
function reply(raw){const q=raw.toLocaleLowerCase("vi").trim();if(/^(google|tìm|tim|tra cứu|search)\s*[:：-]?\s+/.test(q)){search(raw.replace(/^(google|tìm|tim|tra cứu|search)\s*[:：-]?\s+/i,""));return}
if(/google|tìm kiếm|tra cứu|tìm thông tin/.test(q)){say("mo","Để tìm trên Google, bạn gõ “tìm” + nội dung. Ví dụ: tìm phong cách nội thất Japandi 2026. Kết quả mở trong tab mới.");return}
if(/dự án|du an|project/.test(q)){say("mo","Bạn nhấn “＋ Dự án mới” ở thanh trên cùng. Chọn dự án ở ô bên cạnh; dữ liệu được lưu cục bộ trong trình duyệt. Mục Dự án có thể sao lưu và nhập lại dữ liệu.");return}
if(/design|thiết kế|thiet ke|prompt/.test(q)){say("mo","Mở Sáng tạo → Design AI, chọn không gian, phong cách và điền yêu cầu; sau đó nhấn “Phân tích & tạo prompt”. Bạn có thể sao chép kết quả để dùng ở công cụ tạo ảnh.");return}
if(/edit|chỉnh sửa|sửa ảnh/.test(q)){say("mo","Bạn mở Sáng tạo → Edit AI để mô tả phần cần thay đổi, sản phẩm, vật liệu hoặc ánh sáng. Nhớ ghi rõ những yếu tố phải giữ nguyên.");return}
if(/video|camera|góc máy/.test(q)){say("mo","Bạn chọn Video AI để lên kịch bản, shot và hướng chuyển động camera. Bản miễn phí hỗ trợ biên soạn, không trực tiếp kết xuất video AI.");return}
if(/upscale|nâng cấp ảnh|phóng ảnh/.test(q)){say("mo","Chọn Upscale AI trong Xưởng sáng tạo. Chất lượng phụ thuộc công cụ xử lý đang tích hợp; phóng kích thước không đồng nghĩa khôi phục chi tiết bằng mô hình AI.");return}
if(/thuật ngữ|khái niệm/.test(q)){say("mo","Bạn có thể nhập “tìm” kèm thuật ngữ chuyên ngành để tra cứu nguồn trên Google. Tôi chưa có mô hình ngôn ngữ để tự định nghĩa chính xác mọi thuật ngữ.");return}
if(/phong cách|gợi ý/.test(q)){say("mo","Một số hướng thiết kế để bạn tham khảo: Minimal Luxury, Japandi, Contemporary, Biophilic và Warm Modern. Bạn có thể mở Design AI để xây dựng ý tưởng hoặc gõ “tìm xu hướng nội thất 2026” để xem nguồn mới.");return}
if(/xin chào|chào|hello|mỡ ơi|mo oi|yêu|nhớ/.test(q)){say("mo","Xin chào! Tôi có thể chỉ đường trong Studio hoặc mở Google. Bạn thử hỏi “cách tạo dự án”, “Design AI” hay “tìm vật liệu đá tự nhiên” nhé.");return}
say("mo","Thư ký AI chưa có bộ não AI hội thoại trong phiên bản miễn phí này nên không muốn đoán sai. Bạn có thể hỏi cách dùng Studio hoặc gõ “tìm ” trước câu hỏi để tra Google nhé.")}
toggle.addEventListener("click",()=>open(panel.hidden));root.querySelector("#moMin").addEventListener("click",()=>open(false));root.querySelector("#moClose").addEventListener("click",()=>open(false));root.querySelector("#moClear").addEventListener("click",()=>{history=[];try{localStorage.removeItem(KEY)}catch{}say("mo","Thư ký AI đã xóa lịch sử chat trên thiết bị này. Bạn cần Thư ký AI hỗ trợ gì tiếp nào?")});root.querySelector("#moForm").addEventListener("submit",e=>{e.preventDefault();const v=input.value.trim();if(!v)return;input.value="";say("user",v);reply(v)});root.querySelectorAll("[data-mo-quick]").forEach(b=>b.addEventListener("click",()=>{const v=b.dataset.moQuick;say("user",v);reply(v)}));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!panel.hidden)open(false)});draw();
})();